# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets: # Contient la liste des filtres
        carre: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [200, 200] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image
        reduc:
            quality: 85
            filters:
                scale:
                    dim: [ 250, 250 ]
        product:
            quality: 80
            filters:
                upscale:
                    min: [800, 400]
                thumbnail:
                    size: [800, 400]
                    mode: outbound
