vich_uploader:
    db_driver: orm
    mappings:
        Product:
            uri_prefix:         '%uploadsRelativeDir%'
            upload_destination: '%kernel.project_dir%/public/%uploadsRelativeDir%'

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
